### ISSUE TITLE
I seem to have broken my allegiance tree

### ISSUE THREAD

**Issue by immortalbob** [amoeba/treestats.net#44]
http://treestats.net/Morningthaw/He%20who%20is%20called%20I%20Am

cant figure out what character needs the update, i've logged all of the ones i moved in twice now :/

**Comment by amoeba** [comment]
I haven't taken a look yet (on my phone now). I'll take a look later today
when I get time.

**Comment by amoeba** [comment]
The tree will stop searching at 500 members, so there could either be >500 members or you could have a loop somewhere. I changed the code so that it returns the tree no matter what. Your tree now loads but the problem isn't fully solved. Let me know if the tree loads now.

**Comment by immortalbob** [comment]
ok, so i figured out a bug that can cause this...apparently, allegiance info only changes when the patron is logged in.  If i log in a moved vassal to update, it will, but it doesnt remove from the old patron till the old patron logs in.

**Comment by amoeba** [comment]
Ah, that makes sense. I don't check the allegiance information for that level of integrity when a character is updated, though I should. I'll add that as a todo. Thanks for figuring this out for me and sorry for any pain!

**Comment by amoeba** [comment]
Did this tonight -- should be live in the next release of the site. Thanks again for reporting.
